### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by PCSource** [jv110/Lua-make#1]
Title says all

**Comment by jv110** [comment]
Do I really need a license?

**Comment by PCSource** [comment]
Yes. Because I want to modify make with some changes kinda like AppVeyor, but done on the client (In this case, the ComputerCraft computer) so people can easily download my project and build if they choose so. If I just do that without permission from a license, or you, you could sue me and win because of copyright laws

**Comment by jv110** [comment]
When the developer doesn't specify a license, it means they don't really care. They still own the program though, so you can't just redistribute, but it's perfectly OK to distribute it as a modified version of make or just contribute to the original project.

**Comment by PCSource** [comment]
No. No license specified means that no permissions are granted through the license

**Comment by jv110** [comment]
No. No license specified means the user decides. If he doesn't specify what he wants, it's like I said: He owns the program, but doesn't really care what you do with it.

Anyway, I just wrote the license.
